apiVersion: v1
kind: ConfigMap
metadata:
  name: consul-client-config
data:
  client.json: |
    {
      "server": false,
      "leave_on_terminate": true,
      "retry_join": [
          "consul.default.svc.cluster.local"
      ]
    }