---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul-client
  labels:
    app: consul-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul-client
  template:
    metadata:
      labels:
        app: consul-client
    spec:
      containers:
        - name: consul-client
          image: consul:1.6.2
          imagePullPolicy: IfNotPresent
          args:
            - "agent"
            - "-config-file=/etc/consul/config/client.json"
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 500m
              memory: 500Mi
          volumeMounts:
            - name: consul-client-config
              mountPath: /etc/consul/config
          ports:
            - name: http
              containerPort: 8500
            - name: https
              containerPort: 8443
            - name: rpc
              containerPort: 8400
            - name: serflan-tcp
              protocol: "TCP"
              containerPort: 8301
            - name: serflan-udp
              protocol: "UDP"
              containerPort: 8301
            - name: serfwan-tcp
              protocol: "TCP"
              containerPort: 8302
            - name: serfwan-udp
              protocol: "UDP"
              containerPort: 8302
            - name: consuldns
              containerPort: 8600
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
      volumes:
        - name: consul-client-config
          configMap:
            name: consul-client-config
