apiVersion: v1
kind: ConfigMap
metadata:
  name: consul-server-config
data:
  server.json: |
    {
      "acl": {
        "enabled": true,
        "default_policy": "deny",
        "down_policy": "extend-cache"
      },
      "ui": true
    }