apiVersion: v1
kind: ConfigMap
metadata:
  name: consul-config
data:
  server.json: |
    {
        "datacenter": "dc1",
        "server": true,
        "bootstrap": true,
        "client_addr": "0.0.0.0",
        "ui": true,
        "data_dir": "/consul/data",
        "log_level": "INFO",
        "acl": {
            "enabled": true,
            "default_policy": "deny",
            "down_policy": "extend-cache",
            "tokens": {
              "master": "498073a8-5091-4e9e-871a-bbbeb030d1f6"
            }
        }
    }