apiVersion: v1
kind: ConfigMap
metadata:
  name: consul-0-certificates
data:
  consul-agent-ca.pem: |
    -----BEGIN CERTIFICATE-----
    MIIC7DCCApGgAwIBAgIQJ/QSaVUj6pdYxVIN+QS58TAKBggqhkjOPQQDAjCBuDEL
    MAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1TYW4gRnJhbmNpc2Nv
    MRowGAYDVQQJExExMDEgU2Vjb25kIFN0cmVldDEOMAwGA1UEERMFOTQxMDUxFzAV
    BgNVBAoTDkhhc2hpQ29ycCBJbmMuMT8wPQYDVQQDEzZDb25zdWwgQWdlbnQgQ0Eg
    NTMxMDcxODU2OTc3NzM3OTI3NzY1NDU3OTMzODM0NjAwMjY4NjUwHhcNMTkxMTI3
    MTQ0OTU5WhcNMjQxMTI1MTQ0OTU5WjCBuDELMAkGA1UEBhMCVVMxCzAJBgNVBAgT
    AkNBMRYwFAYDVQQHEw1TYW4gRnJhbmNpc2NvMRowGAYDVQQJExExMDEgU2Vjb25k
    IFN0cmVldDEOMAwGA1UEERMFOTQxMDUxFzAVBgNVBAoTDkhhc2hpQ29ycCBJbmMu
    MT8wPQYDVQQDEzZDb25zdWwgQWdlbnQgQ0EgNTMxMDcxODU2OTc3NzM3OTI3NzY1
    NDU3OTMzODM0NjAwMjY4NjUwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAS9qhT5
    TtQ6rZuhL66NBm/Xt+U448/nQF4QX79LeVbDORKm1jYyauOSJ5b2e7e9CmElSXHn
    NiQ81UYukRnmw0c9o3sweTAOBgNVHQ8BAf8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB
    /zApBgNVHQ4EIgQgZ4MDPGK5QL5oB9thXfwMOsHn3/XNo8nmYh2TDCkMIgUwKwYD
    VR0jBCQwIoAgZ4MDPGK5QL5oB9thXfwMOsHn3/XNo8nmYh2TDCkMIgUwCgYIKoZI
    zj0EAwIDSQAwRgIhAIoVb968FaVBxV2V6r9GgosUaDTwO/0s5OMhVOuyD2/oAiEA
    teCHXDcPt1zMTVoPpek8/UYFEZi2aEEGRy/bNGuIk1Q=
    -----END CERTIFICATE-----

  node-pub.pem: |
    -----BEGIN CERTIFICATE-----
    MIICnDCCAkGgAwIBAgIQY2Qzp05ema1FAjdBnpnweDAKBggqhkjOPQQDAjCBuDEL
    MAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1TYW4gRnJhbmNpc2Nv
    MRowGAYDVQQJExExMDEgU2Vjb25kIFN0cmVldDEOMAwGA1UEERMFOTQxMDUxFzAV
    BgNVBAoTDkhhc2hpQ29ycCBJbmMuMT8wPQYDVQQDEzZDb25zdWwgQWdlbnQgQ0Eg
    NTMxMDcxODU2OTc3NzM3OTI3NzY1NDU3OTMzODM0NjAwMjY4NjUwHhcNMTkxMTI3
    MTQ1MzM2WhcNMjAxMTI2MTQ1MzM2WjAcMRowGAYDVQQDExFzZXJ2ZXIuZGMxLmNv
    bnN1bDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABDM/H4+UTtvD2FB0bIcmc8Fm
    4LcUE8SDTKtS1m0mH6nR/c5zCAJs/aoB6xKBuZZmsjX/+tsixGQRDWnMwAeCK6Wj
    gccwgcQwDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEF
    BQcDAjAMBgNVHRMBAf8EAjAAMCkGA1UdDgQiBCAZM7VovVqXrCwaBYl66z8a2bXQ
    Z53G9G2Zg3AVzNiliTArBgNVHSMEJDAigCBngwM8YrlAvmgH22Fd/Aw6weff9c2j
    yeZiHZMMKQwiBTAtBgNVHREEJjAkghFzZXJ2ZXIuZGMxLmNvbnN1bIIJbG9jYWxo
    b3N0hwR/AAABMAoGCCqGSM49BAMCA0kAMEYCIQDxCtJOfMpxH4Zi6dyrAkJgEUIf
    vQ+A7HNcIk+Hv5N4TgIhAMib9q/59PH/aHOLu4C7gKRiZV9Z7qvpNoVcR6D0qu0o
    -----END CERTIFICATE-----

  node-key.pem: |
    -----BEGIN EC PRIVATE KEY-----
    MHcCAQEEIAs6ge6/FritbK1XKr3wZevDy50t33Z8apwImaU/WloJoAoGCCqGSM49
    AwEHoUQDQgAEMz8fj5RO28PYUHRshyZzwWbgtxQTxINMq1LWbSYfqdH9znMIAmz9
    qgHrEoG5lmayNf/62yLEZBENaczAB4IrpQ==
    -----END EC PRIVATE KEY-----
