apiVersion: v1
kind: ConfigMap
metadata:
  name: consul-config
data:
  server.json: |
    {
        "datacenter": "dc1",
        "server": true,
        "bootstrap": true,
        "client_addr": "0.0.0.0",
        "ui": true,
        "data_dir": "/consul/data",
        "log_level": "INFO"
    }
